lookback_days = 7                            # On first run, iterate over n previous days.
txt_alert_enabled = True                     # Write results to 'YYYY-MM-DD_Results.txt'
thehive_alert_enabled = False                # NOT IN USE - FUTURE FEATURE
thehive_url = 'https://thehive.blah.io'      # NOT IN USE - FUTURE FEATURE
webhook_alert_enabled = False                # Enable output to a configured webhook.
webhook_url = 'https://mattermost.blah.io'   # Mattermost or Slack incoming webhook URL.
email_alert_enabled = False                  # Send reports via email.
email_srv = 'smtp.blah.io'                   # SMTP Server/Relay
email_from = 'no-reply@blah.io'              # From Address
email_to = 'security@blah.io'                # To Address